export interface Course {
    CourseMasterID: number;
    CourseName: string;
    LDIntakeOwner: string;
    ProjectManagerContact: string;
    BusinessSponsor: string;
    Descriptions: string;
    InstructionalDesigner: string;
    CourseOwnerID: number;
    ProgramTypeID: number;
    DeliveryTypeID: number;
    TotalCPECredit: string;
    CourseNotes: string;
    Materials: string;
    RoomSetUpComments: string;
    CourseID: string;
    Overview: string;
    Objectives: string;
    MaximumAttendeeCount: number;
    MinimumAttendeeCount: number;
    MaximumAttendeeWaitlist: number
    PrerequisiteCourseID: string;
    EquivalentCourseID: string;
    FirstDeliveryDate: Date;
    LevelofEffort: string;
    Vendor: string;
    ProjectStatusID: number;
    Duration: string;
    Collateral: boolean;
    FocusDomain: string;
    FocusRetired: string;
    FocusDiscFrom: string;
    FocusDisplayedToLearner: string;
    CourseRecordURL: string;
    ServiceNowID: string;
    SubjectMatterProfessional: string;
    IsDeleted: boolean;
    Status: string;
}